name: "actions"
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - labeled
      - unlabeled
permissions: write-all

jobs:
  check-pr-description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jadrol/pr-description-checker-action@v1.0.0
        id: description-checker
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR
        uses: JJ/github-pr-contains-action@releases/v10
        with:
          github-token: ${{github.token}}
          bodyDoesNotContain: "Delete|this"
          bodyContains: "Test"
          diffContains: ";"
          diffDoesNotContain: "TODO|to do"
          filesChanged: 1
          linesChanged: 1
  pr-compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: mtfoley/pr-compliance-action@main
        with:
          # all inputs are optional
          watch-files: |
            README.md
          body-fail: true
          ignore-team-members: false 
          body-auto-close: false
    
