name: "actions"
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - labeled
      - unlabeled

jobs:
  check-pr-description:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jadrol/pr-description-checker-action@v1.0.0
        id: description-checker
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR
        uses: JJ/github-pr-contains-action@releases/v10
        with:
          github-token: ${{github.token}}
          bodyDoesNotContain: "Delete|this"
          bodyContains: "Test"
          diffContains: ";"
          diffDoesNotContain: "TODO|to do"
          filesChanged: 1
          linesChanged: 1
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: hello-world
        run: echo "Hello World!"
