name: "Check PR Description"
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - labeled
      - unlabeled

jobs:
  check-pr-description:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jadrol/pr-description-checker-action@v1.0.0
        id: description-checker
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
